reductstore/web-console

CHANGELOG.md, src/Components/Bucket/CreateOrUpdate.test.tsx, src/Components/Bucket/CreateOrUpdate.tsx
It doesn't work after webpack. See [here]( https://forum.dfinity.org/t/cannot-convert-a-bigint-value-to-a-number/5470/12)
```
2n ** BigInt(somvalue);
```
=> Fix bigint conversions in bucket settings

CHANGELOG.md, src/index.tsx
When we use window.location to figure out the hostname of the storage, we should use static paths but not React.js routes.
=> Fix API and UI paths for embedded console

CHANGELOG.md, src/Views/BucketPanel/BucketDetail.test.tsx, src/Views/BucketPanel/BucketDetail.tsx, src/Views/BucketPanel/BucketList.test.tsx, src/Views/BucketPanel/BucketList.tsx
Closes #22
Bug Fix
We use same field `latestRecord` for  columns `Oldest Record (UTC)` and `Latest Record (UTC)`
We'll use fields `oldestRecord` and `latestRecords` 
No
=> [#22] Fix timestamps for latest records

CHANGELOG.md, src/Views/Dashboard/Dashboard.test.tsx, src/Views/Dashboard/Dashboard.tsx
Closes #27 
Feature
On the dashboard, the buckets are sorted by names.
By last record, so recently updated is shown first.
No
=> [#27] Sort buckets by latest record on dashboard

CHANGELOG.md, src/Components/Bucket/BucketCard.test.tsx, src/Components/Bucket/BucketCard.tsx, src/Helpers/TestHelpers.tsx, src/Views/BucketPanel/BucketDetail.tsx, src/Views/BucketPanel/BucketList.test.tsx, src/Views/BucketPanel/BucketList.tsx, src/Views/Dashboard/Dashboard.tsx
Closes #29
Update
A user can add a new bucket only from dashboard
Now they can add it from `Buckets` page
No
Disable control panel on BucketCard on Dashboard. Now a user can change settings or remove a bucket only from its
detail view.
=> [#29] Add button to `Buckets` page to create a new bucket 

CHANGELOG.md, package-lock.json, package.json
Closes #
Update
We use `reduct-js` == 0.6
`reduct-js` == 0.7
No
=> Update `reduct-js` to 0.7.0

CHANGELOG.md, package-lock.json, package.json
Closes #
Update
The console is using `reduct-js` 0l7 with experimental API
`reduct-js` v1.0.0 with new v1.0 HTT API support
No
=> Update reduct-js to 1.0.0

CHANGELOG.md, Dockerfile, package-lock.json, package.json, src/App.test.tsx, src/App.tsx, src/BackendAPI.ts, src/Components/Bucket/BucketCard.test.tsx, src/Components/Bucket/BucketCard.tsx, src/Components/Routes.tsx, src/Helpers/TestHelpers.tsx, src/Views/Auth/Login.test.tsx, src/Views/BucketPanel/BucketDetail.test.tsx, src/Views/BucketPanel/BucketDetail.tsx, src/Views/BucketPanel/BucketList.test.tsx, src/Views/BucketPanel/BucketList.tsx, src/Views/Dashboard/Dashboard.test.tsx, src/Views/Dashboard/Dashboard.tsx
Closes #48
Feature
See #48 
I check current permission with Client.me() method and hide the control buttons like create/remove a bucket, security panel, and tokens.
No
=> Hide control button if current permissions have no full access

CHANGELOG.md, package-lock.json, package.json, src/Components/Bucket/CreateOrUpdate.test.tsx, src/Components/Bucket/CreateOrUpdate.tsx
Closes #
Update
We use `reduct-js` 1.2 which didn't work with the latest `ReductStore` 1.4
We use the latest `reduct-js` 1.4
No
=> Update reduct-js to 1.4

CHANGELOG.md, src/Views/BucketPanel/BucketDetail.tsx
Closes #60 
Bug fix
See #60 
I've set the  `key` property in the `RemoveConfirmationByName` component so that it is remounted for each entry.
No
=> RS-41: Remount entry confirmation component

CHANGELOG.md, package-lock.json, package.json, src/Components/Replication/CreatOrUpdate.test.tsx, src/Components/Replication/CreateOrUpdate.css, src/Components/Replication/CreateOrUpdate.tsx
Closes #
Feature
Add the new fields 'Every nth record' and 'Once for seconds' to the replication settings form:
No
No
=> RS-319: add downsampling options to Create/Update Replication form

CHANGELOG.md, src/Views/BucketPanel/BucketDetail.test.tsx, src/Views/BucketPanel/BucketDetail.tsx
Closes #
feature
As a user, I can rename entry with Web Console
No
Version 1.12: The rename method was introduced.
=> RS-510: Rename entry with web console

CHANGELOG.md, src/Components/Bucket/BucketSettingsForm.test.tsx, src/Components/Bucket/BucketSettingsForm.tsx
Closes #
Bug fix
The PR adds HARD quota to the bucket settings. I classify it as a bug because we forgot to add the type in the previous release.
[(Add links to related issues)
](https://github.com/reductstore/reductstore/pull/570)
No
=> RS-554: Add hard quota to bucket settings

CHANGELOG.md, src/Components/Bucket/BucketCard.tsx, src/Components/LicenseDetails/LicenseDetails.test.tsx, src/Components/RemoveConfirmationModal.test.tsx, src/Components/RemoveConfirmationModal.tsx, src/Components/Replication/ReplicationCard.tsx, src/Views/BucketPanel/BucketDetail.tsx, src/Views/BucketPanel/BucketList.tsx
Closes #73  
Bug fix
Fix state to ensure that the delete modal can reopen after removing a first bucket
#73 
No
=> RS-582: Bug confirmation window doesn't appear after first bucket removal

CHANGELOG.md, src/Views/BucketPanel/EntryDetail.test.tsx, src/Views/BucketPanel/EntryDetail.tsx
Closes #87 
Bug fix
The PRs initialise the `when' option in the query request, even if a use doesn't set the conditional query. This forces the SDK to correctly use the POST endpoint, which supports fetching records without content.
No
No
=> RS-658: fix server-side channel error for empty conditional query

CHANGELOG.md, src/Components/EditRecordLabelsModal/EditRecordLabelsModal.css, src/Components/EditRecordLabelsModal/EditRecordLabelsModal.tsx, src/Components/EditRecordLabelsModal/index.ts, src/Views/BucketPanel/EntryDetail.test.tsx, src/Views/BucketPanel/EntryDetail.tsx
Closes #90 
Feature: Add record label editing functionality with modal dialog and JSON editor
Added edit icon for each record in the EntryDetail view
Implemented modal dialog showing record metadata (timestamp, content type, size)
Added CodeMirror-based JSON editor for modifying record labels
Implemented full update flow (read original → remove → write with new labels)
Added comprehensive tests for label editing functionality
Fixed how empty conditional queries are handled by setting an empty object ({}) instead of an empty string
Related issues
Feature implementation for record label editing Bug fix: RS-658 - Fix server-side channel error for empty conditional query
(Add links to related issues)
No, these are backward-compatible changes that enhance functionality without requiring …
=> RS-613: Add record label editing functionality with modal dialog and JSON editor

CHANGELOG.md, src/Views/BucketPanel/EntryDetail.test.tsx, src/Views/BucketPanel/EntryDetail.tsx
Closes #
Feature enhancement
- Removed the separate limit input field from the Fetch Records panel
- Added `$limit` parameter directly to the default JSON query condition
- Updated example text to show users how to use the `$limit` operator
- Updated tests to match these changes
#99 Remove "limit" field from Fetch Records Panel
Yes - users will need to use the `$limit` operator in their JSON query conditions instead of the separate limit field. This requires ReductStore server v1.15+.
=> Remove limit field and use  JSON operator in query conditions

CHANGELOG.md, package.json, src/Components/Bucket/BucketCard.test.tsx, src/Components/Entry/UploadFileForm.test.tsx, src/Components/Replication/ReplicationSettingsForm.test.tsx, src/Components/Replication/ReplicationSettingsForm.tsx
Closes #100 
Bug
Bug fix - Ensures that the CodeMirror editor for the "When condition" in ReplicationSettingsForm is properly disabled for provisioned replication.
(Add links to related issues)
No
=> When condition editor made disabled for provisioned replication settings

CHANGELOG.md, src/Components/Replication/ReplicationSettingsForm.test.tsx, src/Components/Replication/ReplicationSettingsForm.tsx, src/Views/BucketPanel/EntryDetail.test.tsx
Closes #105 
Hide legacy feature
Hid the condition fields when `each_n` and `each_s` are null or undefined.
No
No
=> Hide condition fields in replication settings when `each_n` and `each_s` are null or undefined,

CHANGELOG.md, src/Views/SecurityPanel/TokenDetail.tsx
Closes #
Feature
The PR changes the type of bucket select component in the token settings. Now it's possible to enter a custom text for non-existing buckets or wildcards.
https://github.com/reductstore/reductstore/pull/877
No
=> Support for wildcard and custom input for token write/read permissions
