reductstore/web-console

- CHANGELOG.md
- package-lock.json
- package.json
- src/Views/Dashboard/Dashboard.test.tsx
> [#1] Update reduct-js to 0.4.0

- .github/workflows/ci.yml
- CHANGELOG.md
- src/App.css
- src/App.tsx
- src/Views/Dashboard/Dashboard.css
> [#2] Use Reduct's colours for UI

- src/Components/Bucket/Create.test.tsx
- src/Components/Bucket/Create.tsx
- src/Views/Dashboard/Dashboard.test.tsx
- src/Views/Dashboard/Dashboard.tsx
> [#3] Show default settings for a new bucket

- CHANGELOG.md
- src/Components/Bucket/CreateOrUpdate.test.tsx
- src/Components/Bucket/CreateOrUpdate.tsx
> [#12] Use SI sizes for bucket settings

- CHANGELOG.md
- src/Components/Bucket/BucketCard.tsx
- src/Views/Dashboard/Dashboard.tsx
> [#15] Show 2 buckets in row of dashboard

- CHANGELOG.md
- config-overrides.js
- package-lock.json
- package.json
- src/Components/Bucket/CreateOrUpdate.test.tsx
- src/Components/Bucket/CreateOrUpdate.tsx
**Closes** #18 
Feature
The bucket form doesn't have a field for `max_block_records`.
I added the parameter to the form.  Also, I move **Max. Block Records** and **Max Block Size** field to the advanced settings. 
None 
Refactor CHANGELOG.md according [Keep a Changelog](https://keepachangelog.com/en/1.0.0/)
> WIP: [#18] Add `max_block_records` to bucket settings

- CHANGELOG.md
- src/Helpers/ApiUrlParser.test.ts
- src/Helpers/ApiUrlParser.ts
- src/index.tsx
Closes #23
Bug Fix
See #23 
I fixed parsing of `window.location` and added tests
no
> [#23] Fix location parsing

- CHANGELOG.md
- config-overrides.js
- package-lock.json
- package.json
- src/Components/Bucket/BucketCard.test.tsx
- src/Components/Bucket/BucketCard.tsx
- src/Helpers/TestHelpers.tsx
- src/Views/BucketPanel/BucketDetail.tsx
- src/Views/Dashboard/Dashboard.test.tsx
- src/Views/Dashboard/Dashboard.tsx
Closes #28
Feature
User can open bucket details only from `Buckets`
Now they can click on bucket card from `Dashboard`
No
Also update **reduct-js** and remove encryption dependencies.
> [#28] Make bucket card clickable to open bucket details

- CHANGELOG.md
- package.json
- src/App.css
- src/App.tsx
Closes #26
Feature
No information about version which a user is using
A user can see the version on the bottom of the slider
No
> [#26] Show console version on slider

- CHANGELOG.md
- src/Components/Bucket/CreateOrUpdate.test.tsx
- src/Components/Bucket/CreateOrUpdate.tsx
- src/Helpers/TestHelpers.tsx
Closes #37 
Feature
We check only if a bucket name is empty.
We check if the bucket name contains only letters and numbers. If it isn't, we print an error.
(What changes might users need to make in their application due to this PR?)
> Add validation for bucket name

- CHANGELOG.md
- src/Components/Bucket/BucketCard.tsx
Closes #36 
Feature
A user can remove a bucket by mistake. 
A user must type a bucket name before removing it.
No
> Add input field to confirm bucket name

- .github/workflows/ci.yml
- CHANGELOG.md
Closes #35 
Update
We publish only an image for tags
We create a release and upload the built app there
No
> Publish built application on release page

- CHANGELOG.md
- package-lock.json
- package.json
- src/App.test.tsx
- src/App.tsx
- src/Components/Bucket/CreateOrUpdate.test.tsx
- src/Components/Bucket/CreateOrUpdate.tsx
- src/Components/Routes.tsx
- src/Views/BucketPanel/BucketList.test.tsx
- src/Views/BucketPanel/BucketList.tsx
- src/Views/SecurityPanel/TokenDetail.test.tsx
- src/Views/SecurityPanel/TokenDetail.tsx
- src/Views/SecurityPanel/TokenList.test.tsx
- src/Views/SecurityPanel/TokenList.tsx
Closes #
Feature
Since v1.1 Reduct Storage support Token API, but the console doesn't provide any UI for it
A user can see , remove and create tokens.
No
> UI for token management 

- CHANGELOG.md
- src/App.tsx
- src/Helpers/TestHelpers.tsx
- src/Views/BucketPanel/BucketDetail.tsx
- src/Views/BucketPanel/BucketList.tsx
- src/Views/Dashboard/Dashboard.tsx
Closes #47 
Feature
See #47 
I"ve integrated 5 second update for all pages.
No
> Add 5s auto refresh

- .github/workflows/ci.yml
- CHANGELOG.md
Closes #
Update
When we release a new version, we create `tar.gz` archive, which is not working  for the Rust implementation. 
We create a `zip` archive.
No
> Distribute console as zip archive

- CHANGELOG.md
- src/Components/Bucket/CreateOrUpdate.test.tsx
- src/Components/Bucket/CreateOrUpdate.tsx
Closes #55
Bug fix
See #55 
I've fixed handling the quota type field
No
> Fix updating quota type

- CHANGELOG.md
- src/Views/SecurityPanel/TokenDetail.tsx
Closes #
Bug fix
A new token wasn't initialized properly and a user saw an empty page.
No
> Fix token creation

- CHANGELOG.md
- src/Views/SecurityPanel/TokenList.tsx
Closes #
Bug fix
The token view constantly requested token list. I've fixed the `useEffect` hook to request it only once. 
No
No
> RS-314: fix infinite requests for token list

- CHANGELOG.md
- package-lock.json
- package.json
- src/App.css
- src/App.tsx
- src/Views/Replications/ReplicationDetail.test.tsx
Closes #
Update
Migrate from antd v4 to v5
No
No
> Update antd up to 5.18

- CHANGELOG.md
- package-lock.json
- package.json
- src/Components/Entry/EntryCard.css
- src/Components/Entry/EntryCard.test.tsx
- src/Components/Entry/EntryCard.tsx
- src/Components/LicenseDetails/LicenseDetails.test.tsx
- src/Components/Routes.tsx
- src/Views/BucketPanel/BucketDetail.test.tsx
- src/Views/BucketPanel/BucketDetail.tsx
- src/Views/BucketPanel/EntryDetail.css
- src/Views/BucketPanel/EntryDetail.test.tsx
- src/Views/BucketPanel/EntryDetail.tsx
Closes #
feature
Add a view to browse records in an entry
No
No
> RS-580: Browse records in web console

- .github/workflows/ci.yml
- CHANGELOG.md
- src/Components/Entry/EntryCard.tsx
Closes #
Bug fix
Fixed a bug and added build command in CI/CD test step
No
No
> RS-600: Bug building web console

- CHANGELOG.md
- src/Views/BucketPanel/BucketDetail.test.tsx
- src/Views/BucketPanel/BucketDetail.tsx
- src/Views/BucketPanel/BucketList.test.tsx
- src/Views/BucketPanel/BucketList.tsx
- src/Views/BucketPanel/EntryDetail.tsx
- src/Views/Replications/ReplicationDetail.test.tsx
- src/Views/Replications/ReplicationDetail.tsx
- src/Views/Replications/Replications.test.tsx
- src/Views/Replications/Replications.tsx
- src/Views/SecurityPanel/TokenList.test.tsx
- src/Views/SecurityPanel/TokenList.tsx
Closes #
Bug fix
Fix table loading state to display empty table when no data is available
No
No
> RS-603: Bug table loading state when no data is available

- CHANGELOG.md
- src/App.css
- src/App.test.tsx
- src/App.tsx
- src/Components/HelpMenu.test.tsx
- src/Components/HelpMenu.tsx
- src/Views/Dashboard/Dashboard.css
- src/Views/Dashboard/Dashboard.tsx
Closes #
links update
add useful links in the side menu
No
No
> RS-588: Links to documentation and GitHub

- CHANGELOG.md
- package-lock.json
- package.json
- src/Components/Replication/ReplicationSettingsForm.tsx
Closes #94 
Bug  fix
See  https://github.com/reductstore/reduct-js/pull/104
https://github.com/reductstore/reduct-js/pull/104, #94 
No
> Update RuductStore SDK with fixed  start/stop query parameters

- CHANGELOG.md
- src/Views/BucketPanel/EntryDetail.test.tsx
- src/Views/BucketPanel/EntryDetail.tsx
Closes #
Feature
Implemented record deletion functionality in the EntryDetail component with confirmation modal and proper error handling.
(Add links to related issues)
No
> feat(web-console): implement record deletion with UI tests

- src/Components/EditRecordLabelsModal/EditRecordLabelsModal.tsx
- src/Views/BucketPanel/EntryDetail.tsx
Closes #96 
Refactoring - Improved component architecture and separation of concerns
- Removed the client dependency from EditRecordLabelsModal component
- Updated the component to pass new labels to parent component via callback
- Modified EntryDetail component to handle API calls directly
- Improved error handling in both components
- Fixed ESLint issues with unused imports
(Add links to related issues)
No, this is an internal refactoring that maintains the same functionality from the user's perspective.
This refactoring improves code organization by better separating UI concerns from API logic, making the modal component more reusable and the code more maintainable.
> Refactor EditRecordLabelsModal

- CHANGELOG.md
- package-lock.json
- package.json
- src/Views/BucketPanel/EntryDetail.test.tsx
- src/Views/BucketPanel/EntryDetail.tsx
- src/index.css
Closes #95 
Feature
Use streams for downloading large records
No
No
> 95 feature use streams for downloading files

- AGENTS.md
- CHANGELOG.md
- package.json
- src/Components/Entry/UploadFileForm.test.tsx
- src/Components/Entry/UploadFileForm.tsx
- src/Helpers/contentType.test.ts
- src/Helpers/contentType.ts
- src/Views/BucketPanel/EntryDetail.tsx
Closes #104 
Type fix
Handle .mcap files with correct content type on upload and download
No
No
> 104 feature download mcap files with mcap extension

- CHANGELOG.md
- src/App.css
- src/App.tsx
- src/Components/Bucket/BucketCard.css
- src/Components/HelpMenu.test.tsx
- src/Components/HelpMenu.tsx
- src/Views/Auth/Login.css
- src/Views/Dashboard/Dashboard.css
- src/Views/Dashboard/Dashboard.tsx
Closes #115 
Bug fix
- Wrap bucket cards in a flex grid container to fix broken layout
- Collapse the sidebar menu automatically on small screens
- Show the help menu expanded by default on the login screen
- Add consistent margin to the dashboard panel
- Show "No connection" error only after the initial fetch
No
No
> 115 bug layout issues on different browser sizes

- CHANGELOG.md
- package-lock.json
- package.json
- src/Components/Entry/TimeRangeDropdown.test.tsx
- src/Components/Entry/TimeRangeDropdown.tsx
- src/Components/RemoveConfirmationModal.tsx
- src/Views/BucketPanel/EntryDetail.css
- src/Views/BucketPanel/EntryDetail.test.tsx
- src/Views/BucketPanel/EntryDetail.tsx
Closes #116 
Feature
Add presets and custom range selection with the time range dropdown
No
No
> 116 feature improve time range selection in web console
